version: "3"
services:
  db:
    image: postgres:13.1-alpine
    container_name: edgybot-db
    volumes:
      - ${PWD}/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=edgybot_prod
  migrate:
    build: .
    image: ghcr.io/jswny/edgybot:edge
    container_name: edgybot-migrate
    depends_on:
      - db
    command: eval "Edgybot.Release.migrate"
    environment:
      - DATABASE_HOSTNAME=edgybot-db
      - DISCORD_TOKEN
      - OPENAI_API_KEY
  bot:
    image: ghcr.io/jswny/edgybot:edge
    container_name: edgybot
    depends_on:
      - migrate
    environment:
      - DATABASE_HOSTNAME=edgybot-db
      - DISCORD_TOKEN
      - APPLICATION_COMMAND_PREFIX
      - ARCHIVE_HOSTS_PRESERVE_QUERY
      - OPENAI_API_KEY
      - OPENAI_TIMEOUT
      - OPENAI_CHAT_MODELS
      - OPENAI_IMAGE_MODELS
      - OPENAI_IMAGE_SIZES
      - LF_ENABLED
      - LF_API_KEY
      - LF_SOURCE_ID
