version: "3"
services:
  db:
    image: postgres:13.1-alpine
    container_name: edgybot-db
    volumes:
      - ${PWD}/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=edgybot_prod
  migrate:
    image: ghcr.io/jswny/edgybot
    container_name: edgybot-migrate
    depends_on:
      - db
    command: eval "Edgybot.Release.migrate"
    environment:
      - DATABASE_HOSTNAME=edgybot-db
      - DISCORD_TOKEN
  bot:
    build: .
    image: ghcr.io/jswny/edgybot
    container_name: edgybot
    environment:
      - DATABASE_HOSTNAME=edgybot-db
      - DISCORD_TOKEN
