app = 'edgybot'
primary_region = 'ewr'
kill_signal = 'SIGTERM'
kill_timeout = '5s'

[deploy]
release_command = '/app/bin/migrate'

[env]
PHX_HOST = 'edgybot.fly.dev'
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'off'
auto_start_machines = false
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'connections'
hard_limit = 1000
soft_limit = 1000

[[http_service.checks]]
grace_period = "5s"
interval = "10s"
method = "GET"
timeout = "3s"
path = "/"
