name: Fly Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  flyctl-version: "0.3.29"

jobs:
  deploy-beta:
    name: Deploy on Fly Beta
    runs-on: ubuntu-latest
    environment: beta
    concurrency:
      group: deploy-beta
      cancel-in-progress: true
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.flyctl-version }}
      - name: Deploy
        run: flyctl deploy --remote-only --app ${{ vars.FLY_APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-prod:
    name: Deploy on Fly Production
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: deploy-prod
      cancel-in-progress: true
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: ${{ env.flyctl-version }}
      - name: Deploy
        run: flyctl deploy --remote-only --app ${{ vars.FLY_APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
